package skyerr

// LintCode is a single SKY-WF-* lint code with its human-readable description.
type LintCode struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

// RepoCfgLintCodes is the canonical list of SKY-CFG-01x codes for skylence.json.
var RepoCfgLintCodes = []LintCode{
	{"SKY-CFG-010", "skylence.json: failed to read file"},
	{"SKY-CFG-011", "skylence.json: not valid JSON"},
	{"SKY-CFG-013", "skylence.json: ${env:NAME} in scripts is unsupported; use $NAME env vars injected by the runner"},
	{"SKY-CFG-014", "skylence.json: sidecar entry missing name"},
	{"SKY-CFG-015", "skylence.json: sidecar entry missing command"},
	{"SKY-CFG-016", "skylence.json: preview block present but url is empty"},
}

// LintCodes is the canonical list of all SKY-WF-* lint codes, in numeric order.
var LintCodes = []LintCode{
	{"SKY-WF-001", "Workflow parse failure"},
	{"SKY-WF-002", "Validation failure (missing name, steps, etc.)"},
	{"SKY-WF-003", "Workflow name not found"},
	{"SKY-WF-004", "Failed to read workflow dir/file"},
	{"SKY-WF-005", "DAG contains a cycle"},
	{"SKY-WF-006", "Workflow has no steps or nodes"},
	{"SKY-WF-007", ".sky section format error (unclosed, orphan, nested, malformed marker, name collision)"},
	{"SKY-WF-010", "Command .md file not found"},
	{"SKY-WF-011", "Command file parse error"},
	{"SKY-WF-012", "Command file has no prompt body"},
	{"SKY-WF-020", "DAG: duplicate node ID"},
	{"SKY-WF-021", "DAG: depends_on references unknown node"},
	{"SKY-WF-022", "DAG: node has no prompt/command/bash/http/eval"},
	{"SKY-WF-023", "DAG: node depends on itself"},
	{"SKY-WF-024", "DAG: node has more than one execution kind set"},
	{"SKY-WF-030", "Invalid $node.output reference"},
	{"SKY-WF-031", "Failed to parse when condition"},
	{"SKY-WF-032", "Invalid trigger_rule value"},
	{"SKY-WF-033", "Invalid output_style value"},
	{"SKY-WF-034", "http node: url is required"},
	{"SKY-WF-035", "eval: source is required"},
	{"SKY-WF-036", "eval: exactly one assertion required (contains, matches, or equals)"},
	{"SKY-WF-037", "loop body cannot be http, eval, or wait"},
	{"SKY-WF-038", "loop.until requires exactly one of bash or eval"},
	{"SKY-WF-039", "wait.channel is not a valid value"},
	{"SKY-WF-040", "wait.timeout is not a valid duration"},
	{"SKY-WF-041", "chain_from only valid on prompt/command nodes"},
	{"SKY-WF-042", "chain_from not listed in depends_on"},
	{"SKY-WF-043", "chain_from target is not a prompt/command node"},
	{"SKY-WF-044", "Workflow exceeds max node count"},
	{"SKY-WF-045", "JSON Schema validation failure"},
	{"SKY-WF-046", "loop.max exceeds the allowed cap"},
	{"SKY-WF-047", "Bare {{var}} inside a JSON string literal in http.body"},
	{"SKY-WF-048", "Bash sink (eval/source/bash -c) receives $SKY_OUTPUT_<prompt-node>"},
	{"SKY-WF-049", "mcp_servers entry has invalid shape (missing command/url/type)"},
	{"SKY-WF-050", "mcp_servers name collides with a managed server"},
	{"SKY-WF-051", "claude.isolation has an unsupported value"},
	{"SKY-WF-052", "script.runtime is not bun or uv, or deps contain template expansion"},
	{"SKY-WF-053", "Script runtime binary not found on PATH"},
	{"SKY-WF-054", "sandbox.filesystem.allow path is absolute or traverses outside the repo"},
	{"SKY-WF-055", "${env:NAME} ref where NAME not in workflow secrets declaration"},
	{"SKY-WF-056", "${env:} has empty name"},
	{"SKY-WF-057", "${env:NAME} used in an unsupported location (prompt/bash/eval/script)"},
	{"SKY-WF-058", "loop.idle_timeout_ms set on a non-bash body or with a negative value"},
	{"SKY-WF-059", "permissions:interactive requires claude.isolation = loose; --bare suppresses hooks"},
	{"SKY-WF-060", "output_format is not a valid JSON Schema"},
	{"SKY-WF-061", "Bare keyword ultraplan or ultrareview in a prompt; silently no-ops under non-interactive claude -p"},
	{"SKY-WF-062", "learnings config is invalid (conflicting exclude+only, unknown category, invalid max_bytes)"},
	{"SKY-WF-063", "Bash step uses destructive command without safety: requires_permission"},
	{"SKY-WF-064", "invoke.target is dynamic (contains template expression); literal workflow name required"},
	{"SKY-WF-065", "invoke node inside a loop body; not supported in v1"},
	{"SKY-WF-066", "invoke.target resolves to the current workflow (self-invoke not allowed)"},
	{"SKY-WF-067", "invoke.target not found in any workflow tier (repo, workspace, user)"},
	{"SKY-WF-068", "acquire_lock: lock.key is required"},
	{"SKY-WF-069", "acquire_lock/release_lock: lock.ttl is not a valid duration"},
	{"SKY-WF-078", "spawn.workers is empty"},
	{"SKY-WF-079", "spawn worker has an empty id"},
	{"SKY-WF-080", "spawn worker has an empty prompt"},
	{"SKY-WF-081", "spawn.max_wait is not a valid duration"},
	{"SKY-WF-082", "spawn.on_idle must be \"any\" or \"all\""},
	{"SKY-WF-083", "spawn.boundary: read_only is contradictory with own or must_not_edit"},
	{"SKY-WF-084", "spawn.boundary: glob pattern contains ** (unsupported; use single-segment wildcards)"},
	{"SKY-WF-085", "council.members is empty"},
	{"SKY-WF-086", "council member has an empty id or prompt"},
	{"SKY-WF-087", "council.synthesis is empty"},
	{"SKY-WF-088", "council.max_wait is not a valid duration"},
	{"SKY-WF-089", "council.max_budget_usd is negative"},
	{"SKY-WF-091", "review.paths contains an empty string entry"},
	{"SKY-WF-092", "links entry is empty or contains a path separator"},
	{"SKY-WF-093", "trigger.github.check_run.conclusion is not a valid GitHub conclusion value"},
	{"SKY-WF-094", "trigger.github.check_run is set but trigger.github.events does not include \"check_run.completed\""},
	{"SKY-WF-095", "sentry or linear trigger has no events listed"},
	{"SKY-WF-096", "schedule trigger: cron field is required"},
	{"SKY-WF-097", "schedule trigger: cron expression is invalid (standard 5-field: min hour dom mon dow)"},
	{"SKY-WF-098", "schedule trigger: timezone is not a valid IANA location"},
}
